// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhRAfVfbmJD9Z_LTA0STmBXReREYWqiis',
    appId: '1:793206894125:web:01f103b9ca9b00eef112a4',
    messagingSenderId: '793206894125',
    projectId: 'mobscan-7505e',
    authDomain: 'mobscan-7505e.firebaseapp.com',
    storageBucket: 'mobscan-7505e.firebasestorage.app',
    measurementId: 'G-BXJ59B1DLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUwYGXfOLEwM9lIYwYC7vVLrVhvdFUzQ',
    appId: '1:793206894125:android:db1ac0a3b1c29c3df112a4',
    messagingSenderId: '793206894125',
    projectId: 'mobscan-7505e',
    storageBucket: 'mobscan-7505e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNTZYL58M3JqYaKMaXBHMshLgrbbBIyQ4',
    appId: '1:793206894125:ios:ca1f2588701e8ae2f112a4',
    messagingSenderId: '793206894125',
    projectId: 'mobscan-7505e',
    storageBucket: 'mobscan-7505e.firebasestorage.app',
    iosBundleId: 'com.example.mobscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNTZYL58M3JqYaKMaXBHMshLgrbbBIyQ4',
    appId: '1:793206894125:ios:ca1f2588701e8ae2f112a4',
    messagingSenderId: '793206894125',
    projectId: 'mobscan-7505e',
    storageBucket: 'mobscan-7505e.firebasestorage.app',
    iosBundleId: 'com.example.mobscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhRAfVfbmJD9Z_LTA0STmBXReREYWqiis',
    appId: '1:793206894125:web:52bd456f6afcd70cf112a4',
    messagingSenderId: '793206894125',
    projectId: 'mobscan-7505e',
    authDomain: 'mobscan-7505e.firebaseapp.com',
    storageBucket: 'mobscan-7505e.firebasestorage.app',
    measurementId: 'G-QGDN8YYXEC',
  );
}
